Patch 1
governify/bluejay-docs pull request #1
Opened 2023-09-28 10:05 UTC by carnuare

Add Docker Compose quickstart guide.

2023-09-29 15:03 UTC, motero2k requested changes
Nice contibution. Please address the feedback in the comments on `docker-compose-local-quickstart`

2023-09-29 15:03 UTC, motero2k commented on docs/deployment/docker-compose-local-quickstart.md
> +docker-compose -f docker-bluejay/docker-compose-local.yaml --env-file .env down
To stop the containers you should use "stop", not ''down''. ''down'' deletes the containers. That command is used when something has changed (env, docker-compose) and you need  to ''re-compose'' the containers using ''down'' and then ''up''.

You can explain both cases if you want.

2023-09-30 16:04 UTC, carnuare commented on docs/deployment/docker-compose-local-quickstart.md
> +docker-compose -f docker-bluejay/docker-compose-local.yaml --env-file .env down
Thank you for your feedback and clarification regarding the Docker Compose commands. You're absolutely correct, and I appreciate your input.

2023-09-30 16:11 UTC, motero2k approved these changes
Nice!

2023-09-30 16:11 UTC, merged